### ISSUE TITLE
ComponentRegistrar not found in module-core/registration.php:24

### ISSUE THREAD

**Issue by nblanton** [mageplaza/module-core#37]
Upgraded To 2.3.5-p1.  I am getting this error running  "php bin/magento setup:upgrade".

`PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /public_html/vendor/mageplaza/module-core/registration.php:24
Stack trace:
#0 /public_html/vendor/composer/autoload_real.php(73): require()
#1 /public_html/vendor/composer/autoload_real.php(63): composerRequire4e78f2c4a5192a8992e3924ab68ed863('6b5b87bd06fedcf...', '/var/www/vhosts...')
#2 /public_html/vendor/autoload.php(7): ComposerAutoloaderInit4e78f2c4a519208992e3924ab68ed863::getLoader()
#3 /public_html/app/autoload.php(30): include('/var/www/vhosts...')
#4/public_html/app/bootstrap.php(33): require_once('/var/www/vhosts...')
#5/public_html/bin/magento(14): require('/var/www/vhosts...')
#6 {main}
  thrown in /public_html/vendor/mageplaza/module-core/registration.php on line 24
`

**Comment by SolsWebdesign** [comment]
2.4.4 Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in 
/magento2/vendor/mageplaza/module-core/registration.php:24

**Comment by shankarboss** [comment]
I am also facing the same issue when I run composer install / composer update. Can any one got the fix for this issue ?

**Comment by sharonmichou** [comment]
I've the same issue while running composer update, anyone knows how to fix it?
