### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by bery** [mageplaza/module-core#8]
Hello,

I am getting an error as per below

```
a:4:{i:0;s:137:"Notice: Trying to get property of non-object in C:\xampp\htdocs\projects\magento-2\vendor\mageplaza\module-core\Model\Feed.php on line 74";i:1;s:7253:"#0 C:\xampp\htdocs\projects\magento-2\vendor\mageplaza\module-core\Model\Feed.php(74): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 74, Array)
#1 C:\xampp\htdocs\projects\magento-2\vendor\magento\module-admin-notification\Model\Feed.php(138): Mageplaza\Core\Model\Feed->getFeedData()
#2 C:\xampp\htdocs\projects\magento-2\vendor\mageplaza\module-core\Model\Feed.php(57): Magento\AdminNotification\Model\Feed->checkUpdate()
#3 C:\xampp\htdocs\projects\magento-2\vendor\mageplaza\module-core\Observer\PredispatchAdminActionControllerObserver.php(63): Mageplaza\Core\Model\Feed->checkUpdate()
#4 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\Event\Invoker\InvokerDefault.php(73): Mageplaza\Core\Observer\PredispatchAdminActionControllerObserver->execute(Object(Magento\Framework\Event\Observer))
#5 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\Event\Invoker\InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Mageplaza\Core\Observer\PredispatchAdminActionControllerObserver), Object(Magento\Framework\Event\Observer))
#6 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\Event\Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#7 C:\xampp\htdocs\projects\magento-2\var\generation\Magento\Framework\Event\Manager\Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#8 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\App\Action\Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#9 C:\xampp\htdocs\projects\magento-2\vendor\magento\module-backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 C:\xampp\htdocs\projects\magento-2\vendor\magento\module-config\Controller\Adminhtml\System\AbstractConfig.php(59): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#11 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#12 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent('dispatch', Array)
#13 C:\xampp\htdocs\projects\magento-2\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'adminAuthentica...')
#1
```

could you please have a look?

**Comment by imsamthomas** [comment]
It connects to Mageplaza server at https://www.mageplaza.com/notifications.xml
Make sure your server access to that page.

**Comment by bery** [comment]
At the time of creating the issue, I surely had access. All works fine now and I guess that we can close the issue.
